### ISSUE TITLE
Cant install Picasso96.

### ISSUE THREAD

**Issue by martblek** [Chips-fr/uae4arm-rpi#43] opened 2016-11-17 08:59 UTC
Hi,
After latest changes i cannot install P96.
Installer saying something about Segmented mode for zorro II.
Reverted in my local git repo to my working branch which is
b5be69f9cdd6cc9319c0946c39b2d1b4231a8344.

**Comment by martblek** [comment] 2016-11-17 09:03
my HW is RPI2 with ArchlinuxARM

**Comment by Chips-fr** [comment] 2021-09-23 08:21
Not reproduce with latest version. I will close this issue since very old.

**Closed by Chips-fr** 2021-09-23 08:21 UTC
